### ISSUE TITLE
Webp variant generation on every request

### ISSUE THREAD

**Issue by polhec** [webbuilders-group/silverstripe-next-gen-images#2]
Hello,

i have notice a bug in ImageExtension class, where webp variant existance is checked. In line 144 in ImageExtension class,
$filename is generated and we get something like **MyImage.jpg.webp**.

`$filename = $this->owner->getFilename() . '.webp';`

Then in line 130 existancance of webp variant is tested:

`if (!$store->exists($filename . '.webp', $hash, $variant)) {...}`

Here is again added .webp extension to filename, and check is performed for existance of file with name **MyImage.jpg.webp.webp**, which never exists and webp variant generation is performed on every request.

Looks like that obvious fix is to remove second .webp extension addition in exists() function first parameter. I did that and published [pull request](https://github.com/webbuilders-group/silverstripe-next-gen-images/pull/1) some time ago, but after that result from $store->exists(...) was always true and webp variant was not created on first request.

From here on it seems to me that FlysytemAssetStore exists() method do not work as i would expect. 

exists() method calls applyToFileOnFilesystem() method and supplies closure that checks if original file is present and checks if there is a hash match. This closure should be only called if our variant exists i think?

applyToFileOnFilesystem() first checks for file by using explicit fileID. This checks fail as expected and closure is not called. Then it switches to "our FileResolution strategy" as fallback which gives positive result and calls closure, even though .webp variant does not exists and i get positive result from the exists() method.

For now i have created temporary workaround where i disabled this part of file resolution and seems that module works for me, but i have a feeling that this is not appropriate solution.

**Comment by UndefinedOffset** [comment]
What version of Silverstripe are you using?

**Comment by UndefinedOffset** [comment]
As a side one thing that may have fixed that issue you mentioned in your pull was simply checking for the existence of the `.webp` extension on the end of the filename before adding it. Then it would cover both when it is and is not present.

**Comment by polhec** [comment]
Tested on SS CMS versions 4.13.2 and 4.10.2, results are same. 

Webp extension is always added to original filename as it should be, problem is only duplication of extension when passing filename to exists() method.  But if this duplication is removed, exists() method always returns true, even though .webp variant does not exists on filesystem.

Tine Dolžan

**Comment by UndefinedOffset** [comment]
@polhec There's a bit of a weird issue going on here, based on my testing it doesn't seem to be generating it multiple times. Simply throwing a rough debug using `print` after that exists check shows that, the reason is that the `.webp` is treated as a "variant" by Silverstripe so it's stripped. By doubling the `.webp` being passed into the exists check it forces it to actually look for the `.webp` file.

**Comment by polhec** [comment]
Yes, we have a weird issue, but it is on our side. I have installed clean SS 4.13.2, added your module and it works just fine.
Then i installed our module with some stuff, that we need on all projects. And now i have a bug that is described here. For now i dont know what may have caused it exactly, but if this is in any way relevant for your module, i will inform you about it.

Thank you for your help and sorry for false bug report.

**Comment by UndefinedOffset** [comment]
All good :) but for sure let me know

**Comment by polhec** [comment]
Ok, i think i found a way to reproduce the problem we have. Now i'm working with clean SS 4.13.2 install with only next-gen-images module installed.

Everything is OK only when .webp version of originaly uploaded file is created. For examle if we have has_one relation 'TestImage'  => Image::Class and we call in template just $TestImage, it works fine. In that case if filename is MyFile.JPG, MyFile.JPG.webp variant will be generated. 

But if i use any image manipulation method like $TestImage.Fit(200,200) and $TestImage is never called before (or simultaneously) .webp variant of original will not be created. Only in that case regeneration of resized variant happens on every request as it should not.

I hope i described the problem clear enough and kindly ask you to try reproducing it once again.

**Comment by UndefinedOffset** [comment]
Thanks for that, I was able to reproduce the issue with that information. A large part of what's going on here is Silverstripe expects the variant to be BEFORE the file extension not after. What this module is attempting to do it place it after as well as before. Which is causing us to have to fight the assets system all of the time. A challenge to figure out to say the least ;).

We will continue to play with this but it may take time for us to circle back to it. We're happy to take pull requests if you can figure it out. I have a feeling how we're handling the variant of webp is the source of the issue.

**Comment by UndefinedOffset** [comment]
Unfortunately this module is basically a hack in SS 4.x so it's very dodgy at best, I'd recommend upgrading to SS 5.2+ and using the soon to be released 2.0.0 release of this module.
